replicaCount: 1

image:
  repository: quay.io/rh_ee_mrudraia/atlan-ecommerce-frontend
  tag: v10
  pullPolicy: IfNotPresent

env:  # Move env to the top level
  REACT_APP_BACKEND_URL: "10.0.1.89:32001"

backend:
  repository: quay.io/rh_ee_mrudraia/atlan-ecommerce-backend
  tag: v16
  # env:
  #   POSTGRES_HOST: "mypostgres-service"
  #   POSTGRES_PORT: "5432"


# postgresql:
#   image: postgres:latest  # Official PostgreSQL image
  
# Define secret values for PostgreSQL credentials
# secrets:
#   postgres:
#     POSTGRES_USER: "postgres"
#     POSTGRES_PASSWORD: "admin"
#     POSTGRES_DB: "postgres"
service:
  type: NodePort
  frontendPort: 80
  backendPort: 5000
  nodePort: 32000
  backendNodePort: 32001
  # dbPort: 5432
serviceAccount:
  create: true          # Set to false if you don't need a ServiceAccount created
  name: ""              # Name of the ServiceAccount (if empty, Helm will use the default name)
  annotations: {} 

ingress:
  enabled: false       # Set to true if you want to enable ingress
  annotations: {}      # You can add any annotations required for the ingress
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []              # TLS configuration (optional)
resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"